Add minutes from last meeting
conda-forge/conda-forge.github.io pull request #1168
Opened 2020-10-19 13:37 UTC by ericdill

2020-10-19 13:43 UTC, beckermr requested changes

2020-10-19 13:43 UTC, beckermr commented on src/orga/minutes/2020-10-14.md
> +# 2020-10-14 conda-forge core meeting
Why are there two copies?

2020-10-30 20:08 UTC, jakirkham commented on src/orga/minutes/2020-10-14.md
> +# 2020-10-14 conda-forge core meeting
I pushed a commit to drop this

2020-10-30 20:16 UTC, jakirkham commented
Do we also have the minutes from the last meeting somewhere?

2020-10-30 20:18 UTC, beckermr approved these changes

2020-10-30 20:33 UTC, merged

2020-10-30 20:38 UTC, jakirkham commented
Added notes from the last two meetings here: https://github.com/conda-forge/conda-forge.github.io/pull/1177