Fix #1660 : Added 'Prerequisites Section' #1660
conda-forge/conda-forge.github.io pull request #1662
Opened 2022-03-30 02:50 UTC by Hil-dred

This fixes #1660

2022-03-31 08:44 UTC, Hil-dred commented
Hello @beckermr, @BastianZim 

I have added miniforge to the prerequisites section

2022-03-31 16:56 UTC, kathatherine requested changes

2022-03-31 16:56 UTC, kathatherine commented on src/user/introduction.rst
> +Prequisite
You've got a typo here. Also, I'd make the section name plural.

Prerequisites

2022-04-01 20:39 UTC, kathatherine approved these changes
Looks good to me!

2022-04-13 15:40 UTC, Hil-dred commented
Hello @beckermr @kathatherine, kindly review my PR (commit 1f3329d). I have created this PR as a potential solution to issue #1711

2022-04-13 19:33 UTC, kathatherine commented
@Hil-dred Great! But this cheat sheet needs to be in a separate PR than this one since it's for a different issue. Also, please make sure you're making branches for your changes and not just committing into your main branch. This can get pretty complicated otherwise. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches

2024-02-28 10:38 UTC, closed without merging