Update README.md
conda-forge/conda-forge.github.io pull request #1675
Opened 2022-04-01 18:58 UTC by Radhika-Saini

PR Checklist:

- [ ] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

2022-04-01 19:00 UTC, Radhika-Saini commented
want to do some more changes

2022-04-01 19:04 UTC, Radhika-Saini commented
I am Radhika Saini, an outreachy Applicant. 
Work on my 1st issue [#1346](https://github.com/conda-forge/conda-forge.github.io/issues/1346) and Requested PR.

2022-04-06 15:52 UTC, kathatherine requested changes
Okay, review complete! Let me know if you have any questions.

2022-04-06 15:52 UTC, kathatherine commented on src/README.md
> +1. Be kind to others. Do not insult or put down others. Behave professionally.
Ah, I missed coming back to this. Apologies. Turns out this is all fine. NumFocus has a [template](https://github.com/numfocus/numfocus/blob/8759e21481552f213489e3718979ccecf68e9ead/manual/numfocus-coc.md) you can use for codes of conduct, I've learned. I'll finish the review now.

2022-04-06 15:52 UTC, kathatherine commented on src/README.md
> +This is the short version of Code of Conduct. If you want to read more about it check out on [NumFOCUS Code of Conduct](https://numfocus.org/code-of-conduct).
Comma needed between "it" and "check".

Also replace "on" after "check out" with "the".

"If you want to read more about it, check out the NumFOCUS Code of Conduct."

2022-04-06 15:52 UTC, kathatherine commented on src/README.md
> +
There's a lot of unnecessary blank spaces here.

2022-04-06 15:52 UTC, kathatherine commented on src/README.md
> +4. Who the bad actor was, if any
Put a line between item 4 and the sentence on line 72.

2022-04-06 15:52 UTC, kathatherine commented on src/README.md
> +At NumFOCUS events, if a participant engages in behavior that violates this code of conduct, the conference organizers and staff may take any action they deem appropriate..
Same here. A blank line needed between item 11 and the sentence below it.

2022-04-06 15:52 UTC, kathatherine commented on src/README.md
> +No one espousing views or values contrary to the standards of our code of conduct will be permitted to hold any position representing us, including volunteer positions. We have the right and responsi
And here as well. Blank line between item 11 and the paragraph below it.

2022-04-06 15:52 UTC, kathatherine commented on src/README.md
> +
Blank lines at the end of this file should be deleted.

2022-04-06 20:13 UTC, Radhika-Saini commented
Okays, Thanks for the review. Good to see Template, it helps and I will do the changes.

2022-04-09 10:06 UTC, closed without merging