Re-do first paragraph of 'contributing packages'.
conda-forge/conda-forge.github.io pull request #1684
Opened 2022-04-03 18:17 UTC by chicken-biryani

PR Checklist:

- [X] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [X] put any other relevant information below

The first paragraph of ['contributing packages'](https://conda-forge.org/docs/maintainer/adding_pkgs.html) seemed to require clarity. The PR tries to give a clearer picture by giving the title 'Process' to the paragraph and further divides the already existing paragraph into steps so that a person submitting a package knows where they stand.

The outcome:

![Screenshot (50)](https://user-images.githubusercontent.com/41121520/161442191-7a0ceedb-1351-4c26-8aba-5506583d9c7b.png)

PS: I haven't created an issue for the PR and it would be really great if someone could suggest how to make it look better.

2022-04-03 18:22 UTC, chicken-biryani commented
Hi @beckermr @kathatherine and @BastianZim hope this PR is helpful. Would appreciate your feedback.

2022-04-04 19:24 UTC, kathatherine requested changes
I think this will be very helpful. Let me know if you have questions!

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +===================
You should make the length of any header underlines be the same length as the text. Not a horrible thing, but it does cause warnings in the build log that can take up a lot of space and make it difficult to spot other problems.

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +To submit a package to conda-forge one has to follow the steps:
"To submit a package to conda-forge, follow these steps:"

It's better to use what we call second person imperative in documentation. Basically, write like you're giving an order (but in a nice way, of course). :)

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> + To submit a package to the ``conda-forge`` channel, one has to add its recipe and license, with the help of the `staging process <https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-staging
Same second person imperative tense here as above. "To submit a package to the conda-forge channel, add its recipe and license..."

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +* Step 2. Post Staging process.
Leave "staging" lowercase.

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +* Step 1. The staging process (add recipe and license)
If the other two steps end in a period, have one here, too, to be consistent.

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> + To know what happens once a PR has been merged have a look at our `post staging process <https://conda-forge.org/docs/maintainer/adding_pkgs.html#post-staging-process>`_.
Needs a comma between "merged" and "have".

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +* Step 3. Maintaining the package.
Needs a line between the step title and the rest of the text.

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> + Note that contributing a package to ``conda-forge`` makes you the maintainer of that package. A maintainer is responsible for maintaining the feedstock repository and packages as well as their futur
Who does "it" refer to in this paragraph? The maintainer or the feedstock repo?

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +===================
Make sure that header underline is the right length.

2022-04-04 19:24 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +===================
And here, too.

2022-04-05 12:44 UTC, chicken-biryani commented
@kathatherine I have made the changes. A few pointers, I felt adding about the roles of the maintainer in the Process as well as in the Maintainer role was redundant. What do you think?

2022-04-12 23:36 UTC, kathatherine approved these changes
Yes, I agree that was redundant. Thanks so much!

2023-06-24 09:54 UTC, merged