The code of conduct
conda-forge/conda-forge.github.io pull request #1692
Opened 2022-04-07 13:39 UTC by aliveevie

PR Checklist:

- [ ] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

2022-04-12 23:20 UTC, kathatherine requested changes
Thanks so much! You should also make this a .rst file instead of a .md file.

2022-04-12 23:20 UTC, kathatherine commented on aliveevie/code_of_conduct.md
> +# Teams & Roles
And another blank line is needed beneath this header as well.

2022-04-12 23:20 UTC, kathatherine commented on aliveevie/code_of_conduct.md
> +
Did you get the information above from anywhere in particular or did you do some research and put it together?

2022-04-12 23:20 UTC, kathatherine commented on aliveevie/code_of_conduct.md
> +## Sub-Teams
You also need a blank line beneath this header.

2023-06-22 11:13 UTC, jaimergp commented
https://github.com/conda-forge/conda-forge.github.io/pull/1640

2023-06-22 11:13 UTC, closed without merging