Adding Writing Guidelines Section
conda-forge/conda-forge.github.io pull request #1702
Opened 2022-04-09 16:43 UTC by Radhika-Saini

Work on this issue https://github.com/conda-forge/conda-forge.github.io/issues/1680
I have made some changes
Kindly review.

2022-04-11 23:15 UTC, kathatherine requested changes
This is fantastic. Thanks so much. Just a few edits!

2022-04-11 23:15 UTC, kathatherine commented on src/user/contributing.rst
> +===========================
Make sure the header formatting line is the same length as the header title.

2022-04-11 23:15 UTC, kathatherine commented on src/user/contributing.rst
> +1. For submitting or updating conda-build documentation, follow these rules.
Which rules? The rules below, or are you missing a link?

2022-04-11 23:15 UTC, kathatherine commented on src/user/contributing.rst
> +3. Match the technical jargon to the audience's degree of understanding. It's preferable to underestimate rather than overestimate your readers' knowledge. Limit the usage of technical phrases to tho
Ooh, "augment" is a great word, but let's make this as accessible as possible. Maybe "supplement" or "enhance"?

2023-06-22 13:35 UTC, jaimergp commented
Superseded by https://github.com/conda-forge/conda-forge.github.io/pull/1723

2023-06-22 13:35 UTC, closed without merging