Adding Information Prerequisites Code of Conduct
conda-forge/conda-forge.github.io pull request #1703
Opened 2022-04-09 16:52 UTC by Radhika-Saini

I made the changes in the Code of Conduct section.

2022-04-12 17:19 UTC, Radhika-Saini commented
@ssurbhi560 @kathatherine @beckermr Kindly review.

2022-04-12 23:42 UTC, kathatherine requested changes
Thanks! Review done. For future reference, you don't need to close your PRs after being given a review. Please just make the changes and push the new commit to the same branch. Your changes will show up in the PR.

2022-04-13 17:11 UTC, Radhika-Saini commented
@kathatherine  Thanks for the feedback.
I made the changes. Kindly review commit-2.

2022-04-13 19:39 UTC, kathatherine requested changes
Just that one change and you should be good!

2022-04-13 19:39 UTC, kathatherine commented on src/README.md
> +Conda-forge follows the NumFOCUS Code of Conduct-
Let's do a colon (:) instead of a hyphen (-), please.

2022-04-18 18:35 UTC, kathatherine approved these changes
Looks good. Thanks!

2023-06-22 13:36 UTC, jaimergp commented
Superseded by #1640

2023-06-22 13:36 UTC, closed without merging