Fix-issue #1346- added code of conduct linking
conda-forge/conda-forge.github.io pull request #1718
Opened 2022-04-15 06:03 UTC by ejangphoebe00

PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] put any other relevant information below

2022-04-15 06:04 UTC, ejangphoebe00 commented
@kathatherine fix for issue #1346

2022-04-18 18:55 UTC, kathatherine requested changes
Thanks! The links need to change.

2022-04-18 18:55 UTC, kathatherine commented on src/README.md
> +## conda-forge CODE OF CONDUCT ([https://conda-forge.org/docs/orga/governance.html#code-of-conduct])
The best way to do a link is to pick some text to be the link text and then hide the URL. So this one above could be:

```conda-forge [Code of Conduct](https://conda-forge.org/docs/orga/governance.html#code-of-conduct)```

2022-04-18 18:55 UTC, kathatherine commented on src/README.md
> +Conda-forge adheres to the NumFOCUS Code of Conduct.([https://www.numfocus.org/code-of-conduct])
Same thing with this link:

```Conda-forge adheres to the [NumFOCUS Code of Conduct](https://www.numfocus.org/code-of-conduct).```

2022-04-18 18:55 UTC, kathatherine commented on src/README.md
> +  The Code of Conduct Reporting Form can be accessed here ([https://numfocus.typeform.com/to/ynjGdT])
And here as well:

```The Code of Conduct Reporting Form can be accessed [here](https://numfocus.typeform.com/to/ynjGdT).```

2022-04-18 18:55 UTC, kathatherine commented on src/README.md
> +  >> Diversity Statement([https://numfocus.org/code-of-conduct#diversity-statement])
And all of these links here and below as well.

2023-06-22 11:16 UTC, jaimergp commented
Superseded by https://github.com/conda-forge/conda-forge.github.io/pull/1640

2023-06-22 11:16 UTC, closed without merging