#1705-glossary additions
conda-forge/conda-forge.github.io pull request #1726
Opened 2022-04-18 19:50 UTC by Uma-95

hello @kathatherine 
This is the change that I have made for #1705 
https://github.com/conda-forge/conda-forge.github.io/compare/main...Uma-95:1705-glossary-additions?expand=1
Kindly review.

2022-05-25 05:40 UTC, jakirkham approved these changes

2022-05-25 05:40 UTC, jakirkham commented
Powercycling for CI

2022-05-25 21:07 UTC, kathatherine requested changes

2022-05-25 21:07 UTC, kathatherine commented on src/misc/00_intro.rst
> +     **C**\ onda **P**\ ackage.A conda package is a .conda file that contains system-level libraries,Python or other modules,executable programs and other components,metadata under the info/ director
There's some spacing issues here. Needs a space between the period and "A" at the beginning of the first sentence, and after each comma.

2022-05-25 21:07 UTC, kathatherine commented on src/misc/00_intro.rst
> +     **C**\ onda **C**\hannels.Conda channels are the locations where packages are stored. They serve as the base for hosting and managing packages.Conda-Forge is a conda channels.
Same here. Need a space after each period.

Also "channels" at the very end of this definition should not be plural.

2023-06-24 10:08 UTC, jaimergp commented on src/user/introduction.rst
> +You can refer to the glossary `here<https://conda-forge.org/docs/misc/00_intro.html#glossary>`.
```suggestion
```

I don't think this is the place to put this reference

2023-06-24 10:08 UTC, merged

2023-06-24 10:09 UTC, jaimergp commented on src/user/introduction.rst
> +You can refer to the glossary `here<https://conda-forge.org/docs/misc/00_intro.html#glossary>`.
Oops, this will break the CI I think @jakirkham. I don't think it's a valid RST ref.

2023-06-24 10:16 UTC, jaimergp commented on src/user/introduction.rst
> +You can refer to the glossary `here<https://conda-forge.org/docs/misc/00_intro.html#glossary>`.
It didn't break but it doesn't render nicely. See last line in https://conda-forge.org/docs/user/introduction.html#why-conda-forge