Add "Becoming a Maintainer" link under "Update the recipe" section.
conda-forge/conda-forge.github.io pull request #1764
Opened 2022-06-01 10:03 UTC by ssurbhi560

Towards #1331 

PR Checklist:

- [ ] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

2022-06-01 10:14 UTC, ssurbhi560 commented
@kathatherine @jakirkham @viniciusdc, I was not sure, if I should add the link in the fourth bullet point where it is mentioned that ``Edit the recipe as desired. You may even consider adding yourself as a recipe maintainer.`` or if I should add it at the end of the section. So, I have added it at the end of the section, please let me know what you folks think and if I should add it in the same bullet point.

2022-06-02 23:02 UTC, kathatherine requested changes

2022-06-02 23:02 UTC, kathatherine commented on index.html.tmpl
> +                        If you would like to know how to become a maintainer for a feedstock, please visit <a href="https://conda-forge.org/docs/orga/guidelines.html#becoming-a-maintainer">here</a> t
I think "go" instead of "visit" would read better.

2022-06-03 18:47 UTC, kathatherine approved these changes
LGTM! @beckermr, any opinions?

2022-06-03 19:21 UTC, beckermr commented
LGTM!

2022-06-03 19:21 UTC, merged

2022-06-03 19:51 UTC, jakirkham commented
Thanks Surbhi! 🙏