add extra section-recipe maintainer and feedstock-name
conda-forge/conda-forge.github.io pull request #1772
Opened 2022-06-10 12:03 UTC by ssurbhi560

Closes #1769 and #1331 

PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

2022-06-10 12:18 UTC, beckermr approved these changes

2022-06-13 14:46 UTC, kathatherine requested changes
Just one thing! Otherwise, it looks great

2022-06-13 14:46 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +If you want the name of the feedstock different from the package name in the staged-recipes, you can use the ``feedstock-name`` directive in the recipe of that package, like this:
Let's put "to be" in front of "different"

2022-06-14 20:07 UTC, kathatherine approved these changes
LGTM!

2022-06-14 20:07 UTC, kathatherine commented
@beckermr You good with merging this?

2022-06-14 20:09 UTC, beckermr approved these changes

2022-06-14 20:09 UTC, merged

2022-06-14 22:11 UTC, jakirkham commented
This is great! Thank you 🙏