Add Feedstock repository structure section
conda-forge/conda-forge.github.io pull request #1786
Opened 2022-06-17 09:38 UTC by ssurbhi560

Closes #803 

PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

2022-06-17 10:07 UTC, beckermr reviewed
Some changes for clarity.

2022-06-17 10:07 UTC, beckermr commented on src/maintainer/adding_pkgs.rst
> +Once the PR having the recipe for a package is merged in the ``staged-recipes`` repository, a new repository is created automatically called ``<package-name> feedstock`` which lies in the `feedstock
```suggestion
Once the PR having the recipe for a package is merged in the ``staged-recipes`` repository, a new repository is created automatically called ``<package-name>-feedstock``.
```

2022-06-17 10:07 UTC, beckermr commented on src/maintainer/adding_pkgs.rst
> +A feedstock is made up of a conda recipe (the instructions on what and how to build the package) and the necessary configuration files for automatic building using freely available continuous integra
```suggestion
A feedstock is made up of a conda recipe (the instructions on what and how to build the package) and the necessary configuration files for automatic builds using freely available continuous integration services.
```

2022-06-17 10:07 UTC, beckermr commented on src/maintainer/adding_pkgs.rst
> +Each feedstock contains various files which are generated automatically using `conda-smithy <https://github.com/conda-forge/conda-smithy/>`__ which is a tool used for managing continuous integration
```suggestion
Each feedstock contains various files which are generated automatically using our automated provisioning tool `conda-smithy <https://github.com/conda-forge/conda-smithy/>`__. Broadly every feedstock has the following files: 
```

2022-06-17 10:07 UTC, beckermr commented on src/maintainer/adding_pkgs.rst
> +This folder contians the ``meta.yaml`` file in which everything is defined that is required to build and use the package.
```suggestion
This folder contains the ``meta.yaml`` file and any other files/scripts needed to build the package.
```

2022-06-17 10:07 UTC, beckermr commented on src/maintainer/adding_pkgs.rst
> +This is an auto-generated license which is generated when feedstock is created. This license is different from the related package license, which you define while submitting the package recipe using
```suggestion
This file is the license for the recipe itself. This license is different from the package license, which you define while submitting the package recipe using ``license_file`` in the ``meta.yaml`` file.
```

2022-06-17 10:07 UTC, beckermr commented on src/maintainer/adding_pkgs.rst
> +These are the CI configuration files for service providers like CircleCI, AppVeyor and TravisCI, which makes it possible to build and upload installable packages to the conda-forge Anaconda-Cloud cha
```suggestion
These are the CI configuration files for service providers like Azure and TravisCI.
```

2022-06-17 10:07 UTC, beckermr commented on src/maintainer/adding_pkgs.rst
> +This file is used to configure how conda-forge is set up and built. Making any changes in this files usually requires `rerending of the feedstock <https://conda-forge.org/docs/maintainer/updating_pkg
```suggestion
This file is used to configure how the feedstock is set up and built. Making any changes in this file usually requires `rerending of the feedstock <https://conda-forge.org/docs/maintainer/updating_pkgs.html#dev-update-rerender>`__.
```

2022-06-17 10:07 UTC, beckermr commented on src/maintainer/adding_pkgs.rst
> +This folder contains build scripts for various environments.
```suggestion
```

2022-06-17 20:41 UTC, beckermr approved these changes

2022-06-17 20:42 UTC, beckermr commented
any comments here @kathatherine?

2022-06-19 22:33 UTC, kathatherine requested changes
A few comments. Thanks so much for clearing all this up!

2022-06-19 22:33 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +Each feedstock contains various files which are generated automatically using our automated provisioning tool `conda-smithy <https://github.com/conda-forge/conda-smithy/>`__. Broadly every feedstock
```suggestion
Each feedstock contains various files that are generated automatically using our automated provisioning tool `conda-smithy <https://github.com/conda-forge/conda-smithy/>`__. Broadly, every feedstock has the following files:
```

2022-06-19 22:33 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +Once the PR having the recipe for a package is merged in the ``staged-recipes`` repository, a new repository is created automatically called ``<package-name>-feedstock``.
I feel like "having" isn't the best word here. Maybe "containing" or just "for", though then we could have two instances of the word "for" pretty close together. Up to you.

2022-06-19 22:33 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +A feedstock is made up of a conda recipe (the instructions on what and how to build the package) and the necessary configuration files for automatic builds using freely available continuous integrati
Let's add "(CI)" after "continuous integration", since we mention CI configuration files later in this section. That will make things more clear.

2022-06-19 22:33 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +This file is used to configure how the feedstock is set up and built. Making any changes in this file usually requires `rerending of the feedstock <https://conda-forge.org/docs/maintainer/updating_pk
```suggestion
This file is used to configure how the feedstock is set up and built. Making any changes in this file usually requires `rerendering the feedstock <https://conda-forge.org/docs/maintainer/updating_pkgs.html#dev-update-rerender>`__.
```

2022-06-21 20:00 UTC, kathatherine requested changes

2022-06-21 20:00 UTC, kathatherine commented on src/maintainer/adding_pkgs.rst
> +This file is used to configure how the feedstock is set up and built. Making any changes in this file usually requires `rerending the feedstock <https://conda-forge.org/docs/maintainer/updating_pkgs.
Should be "rerendering", not "rerending" in that link text.

2022-06-23 15:23 UTC, kathatherine commented
@beckermr This looks good to merge.

2022-06-23 15:49 UTC, merged