Add information on using ``arch_rebuild.txt``
conda-forge/conda-forge.github.io pull request #1794
Opened 2022-07-04 10:11 UTC by ssurbhi560

Closes #1668 

PR Checklist:

- [x] make all edits to the docs in the `src` directory, not in `docs` or in the html files
- [x] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [x] put any other relevant information below

2022-07-06 12:04 UTC, jaimergp commented on src/maintainer/knowledge_base.rst
> +You can add a feedstock to ``arch-rebuild.txt`` if it requires rebuilding with different architectures/platforms (such as ppc64le or aarch64).
I would clarify that you need to open a PR on https://github.com/conda-forge/conda-forge-pinning-feedstock to propose changes to that file.

2022-07-15 20:45 UTC, kathatherine requested changes
Just a few changes. Thanks so much!

2022-07-15 20:45 UTC, kathatherine commented on src/maintainer/infrastructure.rst
> +in `arch_rebuild.txt file <https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt>`__.
```suggestion
in the `arch_rebuild.txt file <https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt>`__.
```

2022-07-15 20:45 UTC, kathatherine commented on src/maintainer/infrastructure.rst
> +Read :ref:`using_arch_rebuild` to learn more on how it works.
```suggestion
Read :ref:`using_arch_rebuild` to learn more.
```

2022-07-15 20:45 UTC, kathatherine commented on src/maintainer/knowledge_base.rst
> +You can add a feedstock to ``arch-rebuild.txt`` if it requires rebuilding with different architectures/platforms (such as ppc64le or aarch64). To add the feedstock to ``arch_rebuild.txt``, you would
```suggestion
You can add a feedstock to ``arch-rebuild.txt`` if it requires rebuilding with different architectures/platforms (such as ppc64le or aarch64). To add the feedstock to ``arch_rebuild.txt``, open a PR to the `conda-forge-pinning-feedstock repository <https://github.com/conda-forge/conda-forge-pinning-feedstock>`__.
```

2022-07-15 20:45 UTC, kathatherine commented on src/maintainer/knowledge_base.rst
> +After adding the feedstock to the ``arch_rebuild.txt`` file, the migration bot goes through the list of feedstocks and opens a migration PR for the feedstocks and their dependencies, enabling the aar
```suggestion
Once the PR is merged, the migration bot goes through the list of feedstocks in ``arch_rebuild.txt`` and opens a migration PR for any new feedstocks and their dependencies, enabling the aarch64/ppc64le builds.
```

2022-07-15 20:45 UTC, kathatherine commented on src/maintainer/knowledge_base.rst
> +After adding the feedstock to the ``arch_rebuild.txt`` file, the migration bot goes through the list of feedstocks and opens a migration PR for the feedstocks and their dependencies, enabling the aar
Hey, @leofang, just making sure my changes to this paragraph are correct.

2022-07-16 04:55 UTC, jakirkham commented
cc @leofang (in case you would like to take a look as well :)

2022-07-17 23:48 UTC, leofang commented
Thanks for the ping. The suggested changes look good to me.

2022-07-22 19:09 UTC, leofang approved these changes

2022-07-23 00:09 UTC, jakirkham commented
@kathatherine, do you have any more thoughts on this one? 🙂

2022-07-25 19:01 UTC, kathatherine commented
@jakirkham Nope, looks good to me! Feel free to merge in. Thanks for the review, @leofang!

2022-07-25 19:11 UTC, merged

2022-07-25 19:11 UTC, jakirkham commented
Thanks all! 🙏