Added Element rooms' links
conda-forge/conda-forge.github.io pull request #1937
Opened 2023-04-19 06:11 UTC by mhmohona

Fixes -  #1677
Added info about element rooms for [Get in touch](https://conda-forge.org/docs/orga/getting-in-touch.html?highlight=gitter) page.

2023-04-19 10:32 UTC, beckermr requested changes
Thanks for this PR! All gitter rooms are available from element now. They are actually one and the same. I think we'll need to adjust the PR to somehow reflect this.

2023-04-19 10:32 UTC, beckermr commented on src/orga/getting-in-touch.rst
> +* `element: general <https://app.element.io/#/room/#conda-forge-space:matrix.org>`__: A general chat room for all things conda-forge on Element.
```suggestion
* `element: conda-forge-space <https://app.element.io/#/room/#conda-forge-space:matrix.org>`__: An element space listing all conda-forge rooms.
```

2023-04-19 10:32 UTC, beckermr commented on src/orga/getting-in-touch.rst
> +* `element: community <https://app.element.io/#/room/#conda-forge:matrix.org>`__: Public chat room for the conda-forge community to discuss anything related to conda-forge.
```suggestion
* `element: general <https://app.element.io/#/room/#conda-forge:matrix.org>`__: Public chat room for the conda-forge community to discuss anything related to conda-forge.
```

2023-04-19 16:44 UTC, jakirkham reviewed
Maybe something like this?

2023-04-19 16:44 UTC, jakirkham commented on src/orga/getting-in-touch.rst
```suggestion

Note: All Gitter room links forward to Element

```

2023-04-19 18:23 UTC, beckermr commented on src/conf.py
> +    r'https://matrix.io/#.*$',  # anchors are generated dynamically
```suggestion
    r'https://matrix.to/#.*$',  # anchors are generated dynamically
```

2023-04-19 18:23 UTC, beckermr approved these changes

2023-04-19 18:26 UTC, merged

2023-04-19 18:29 UTC, jakirkham commented
Thanks Mahfuza & Matt! 🙏

2023-04-20 08:01 UTC, jaimergp commented
There are a few more instances of Gitter being mentioned which, I believe, should be replaced by Element/Matrix to avoid confusion.

See this [search query](https://github.com/search?q=repo%3Aconda-forge%2Fconda-forge.github.io+gitter+path%3A*.rst&type=code).

It might be worth considering opening a 2nd PR as a follow-up!