Replace Gitter with Element
conda-forge/conda-forge.github.io pull request #1952
Opened 2023-04-28 16:58 UTC by mhmohona

As per mentioned [here](https://github.com/conda-forge/conda-forge.github.io/pull/1937#issuecomment-1515894289) - follow-up for https://github.com/conda-forge/conda-forge.github.io/pull/1937 

Replacing Gitter channel's link with Element chatroom's link.

2023-04-28 17:18 UTC, jaimergp commented on src/maintainer/maintainer_faq.rst
> +  If you don't receive an an answer after a couple of days, feel free to reach out to us via the public `element <https://app.element.io/#/room/#conda-forge:matrix.org>`__ chatroom.
```suggestion
  If you don't receive an an answer after a couple of days, feel free to reach out to us via the public `Element <https://app.element.io/#/room/#conda-forge:matrix.org>`__ chatroom.
```

2023-04-28 17:19 UTC, jaimergp commented on src/maintainer/updating_pkgs.rst
> +- Build issues that a feedstock configuration update will fix (follow us on `element <https://app.element.io/#/room/#conda-forge:matrix.org>`_ to know about those).
```suggestion
- Build issues that a feedstock configuration update will fix (follow us on `Element <https://app.element.io/#/room/#conda-forge:matrix.org>`_ to know about those).
```

2023-04-28 17:19 UTC, jaimergp commented on src/maintainer/updating_pkgs.rst
> +To contact core, ping them by mentioning @conda-forge/core in a comment or, if you haven't heard back in a while or are new to conda-forge, contact them through the community `element <https://app.el
```suggestion
To contact core, ping them by mentioning @conda-forge/core in a comment or, if you haven't heard back in a while or are new to conda-forge, contact them through the community `Element chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__.
```

2023-04-28 17:20 UTC, jaimergp commented on src/orga/governance.rst
> +           sent to the core email list in a manner similar to the element chatroom: at least 3 times,
Not sure about these editions. This is our governance, so maybe we need to do this through other processes.

2023-04-28 17:20 UTC, jaimergp commented on src/orga/joining-the-team.rst
> +`Element Chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__.
```suggestion
`Element chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__.
```

2023-04-28 17:20 UTC, beckermr commented
cc @conda-forge/core there are a few innocuous changes to the governance document in this PR. Please take a look and object if you feel strongly!

2023-04-28 17:20 UTC, jaimergp commented on src/orga/joining-the-team.rst
> +`Element Chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__.
```suggestion
`Element chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__.
```

2023-04-28 17:21 UTC, jaimergp commented on src/user/announcements.rst
> +our `Element Chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`_, or it's `Matrix/Element
```suggestion
our `Element chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`_, or it's `Matrix/Element 
```

Now we have two mentions to the same thing in the same sentence. 

But, once again, this is an announcement, so we shouldn't touch it.

Revert please. Thanks!

2023-04-28 17:21 UTC, jaimergp commented on src/user/announcements.rst
> +our `Element Chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`_, or it's `Matrix/Element
And the same applies to the rest of the file.

2023-04-28 17:21 UTC, jaimergp commented on src/user/faq.rst
> +  Please join us on our `Element Chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__. We are always happy to answer questions and help beginners.
```suggestion
  Please join us on our `Element chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__. We are always happy to answer questions and help beginners.
```

2023-04-28 17:21 UTC, jaimergp commented on src/user/how_to_get_help.rst
> +Element Chatroom
```suggestion
Element chatroom
```

2023-04-28 17:22 UTC, jaimergp commented on src/user/how_to_get_help.rst
> +If you are just starting out with conda-forge and/or feel completely lost, we recommend getting in touch through `Element Chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__. Our comm
```suggestion
If you are just starting out with conda-forge and/or feel completely lost, we recommend getting in touch through `Element chatroom <https://app.element.io/#/room/#conda-forge:matrix.org>`__. Our community members will direct
```

2023-04-28 17:23 UTC, jaimergp requested changes
Thank you for the changes!

We need to revert a couple files (the announcements, basically), and we need to consult Core on the governance changes.

The rest is just for consistency in the capitalization.

Thanks again!

2023-05-02 09:40 UTC, jaimergp approved these changes
<3

2023-05-02 10:53 UTC, merged