Render conda-forge.yml docs from (WIP) JSON schema
conda-forge/conda-forge.github.io pull request #2095
Opened 2024-03-01 02:38 UTC by jaimergp

PR Checklist:

- [ ] note any issues closed by this PR with [closing keywords](https://help.github.com/articles/closing-issues-using-keywords)
- [ ] if you are adding a new page under `docs/`, you have added it to the sidebar in `docs/sidebar.json`
- [ ] put any other relevant information below
- Part of #1971 
- Experimenting with an alternative to #2010. 
- Depends on https://github.com/conda-forge/conda-smithy/pull/1756.

This generates lightweight docs for `conda-forge.yml`. I've ignored the type information because it can get really complicated (some recursion and nested objects). There are libraries that can help there, but all of them were too intricate for our purposes. This mimics what we have currently :)

Pros:
- JSON Schema is fetched live. No need to rebuild the site if conda-smithy got updated.
Cons:
- Rendered at client side, so we don't have a sidebar (Docusaurus limitation) for now. Might try to do a server side render that can be updated in client side later. This also makes the anchor tests fail for now.

2024-03-01 14:56 UTC, jaimergp commented on docs/maintainer/conda_forge_yml.mdx
> +```
This should be part of the schema docs, not here.

2024-03-12 13:56 UTC, jaimergp commented
With https://github.com/conda-forge/conda-smithy/pull/1756 merged, this is now pulling from conda-smithy @ main, so this is ready for a final review and merge.

2024-03-12 14:08 UTC, beckermr requested changes

2024-03-12 14:08 UTC, beckermr commented on .ci_scripts/update_docs
> +  # TODO^: replace with the real URL once the PR is merged
This needs to be addressed.

2024-03-12 14:12 UTC, jaimergp commented on .ci_scripts/update_docs
> +  # TODO^: replace with the real URL once the PR is merged
Oops, good catch! Thanks!

2024-03-12 14:34 UTC, beckermr approved these changes
Lgtm! This is great and thank you!

2024-03-12 16:42 UTC, beckermr commented on .ci_scripts/update_docs
> +  "https://raw.githubusercontent.com/conda-forge/conda-smithy/main/conda_smithy/data/conda-forge.json"
It should be from the latest release, but I discussed above with @jaimergp and we decided to punt on latest release for future work.

2024-03-12 22:08 UTC, h-vetinari commented
This is very cool! 🤩 

Was just browsing a bit, but I think the dict for `os_version` is wrong (contains arches):
![image](https://github.com/conda-forge/conda-forge.github.io/assets/33685575/f4ad52a0-6d15-4cee-b8fa-3a2098d01829)

2024-03-13 08:11 UTC, jaimergp commented
> Was just browsing a bit, but I think the dict for `os_version` is wrong (contains arches):

Do you mean it should just be `linux`? I think it does need the arch. [Examples in conda-forge](https://github.com/search?type=code&q=os_version+org%3Aconda-forge+path%3Aconda-forge.yml).

2024-03-13 08:13 UTC, jaimergp commented on .ci_scripts/update_docs
> +  "https://raw.githubusercontent.com/conda-forge/conda-smithy/main/conda_smithy/data/conda-forge.json"
I think the "vendored" version should be the released one (so people can use it as an autocomplete driver on their IDE), but then we fetch from `main` on every page load. However, there's no release now that features the schema, so we can change this when there's a new release.

2024-03-13 08:59 UTC, jaimergp commented on .ci_scripts/update_docs
> +  "https://raw.githubusercontent.com/conda-forge/conda-smithy/main/conda_smithy/data/conda-forge.json"
I'll merge and once there's a release we can update this line to `latest`. We might need an API call for that, or maybe push the file to GH Releases for simplicity 🤔

2024-03-13 09:00 UTC, merged